version: '3.8'
services:
  cv-gregory-leterte:
    image: nginx:alpine
    container_name: cv-gregory-leterte
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
