version: '3.8'

services:
  cv-gregory-leterte:
    build: .
    container_name: cv-gregory-leterte
    ports:
      - "8080:80"
    restart: unless-stopped
    
    # Labels pour Portainer distant
    labels:
      - "com.docker.compose.project=cv-gregory-leterte"
      - "project.name=CV Gregory Le Terte"
      - "project.description=Site CV professionnel - Expert IA & Consultant"
      - "project.version=1.0.0"
      - "project.maintainer=gregory.leterte@gmail.com"
      - "environment=production"
      - "type=website"
      - "webserver=nginx"
      - "deployment=remote"
    
    # Variables d'environnement
    environment:
      - TZ=Europe/Paris
