version: '3.8'

services:
  cv-gregory-leterte:
    build: .
    container_name: cv-gregory-leterte
    ports:
      - "80:80"  # Port 80 direct pour production
    restart: unless-stopped
    environment:
      - NGINX_HOST=cv.leterte.fr  # Votre domaine
      - NGINX_PORT=80
    labels:
      # Labels pour Traefik (si utilisé)
      - "traefik.enable=true"
      - "traefik.http.routers.cv.rule=Host(`cv.leterte.fr`)"
      - "traefik.http.routers.cv.entrypoints=websecure"
      - "traefik.http.routers.cv.tls.certresolver=letsencrypt"
      - "traefik.http.services.cv.loadbalancer.server.port=80"
      
      # Labels pour monitoring (optionnel)
      - "com.centurylinklabs.watchtower.enable=true"
      
    networks:
      - web
    volumes:
      # Logs persistants (optionnel)
      - ./logs:/var/log/nginx
    
    # Limites de ressources
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

networks:
  web:
    external: true
