version: '3.8'

services:
  cv-gregory-leterte:
    build: .
    container_name: cv-gregory-leterte
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cv.rule=Host(`cv.votre-domaine.com`)"
      - "traefik.http.routers.cv.entrypoints=web"
      - "traefik.http.services.cv.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
